// Translation dictionary — plain JS, no JSX. Loaded as <script src="strings.jsx"> before React.
// window.tStr(key, lang, type) is the resolver used by every screen.

(function () {
  var MAYA_STRINGS = {
    en: {
      // ── Home ──────────────────────────────────────────────────
      greeting:          'Good morning',
      taraIsHere:        'Tara is here',
      taraHeroSub:       "I'm right here with you today. Tap to talk.",
      chatWithTara:      'Chat with Tara',
      voice:             'Voice',
      babyThisWeek:      'Baby this week',
      sizeOfA:           'The size of a',
      weeksToGo:         '{n} weeks to go',
      weeksPostpartum:   '{n} weeks postpartum',
      monthOf9:          'Month {n} of 9',
      trimester1:        'First trimester',
      trimester2:        'Second trimester',
      trimester3:        'Third trimester',
      todaysCare:        "Today's care",
      checkWater:        'Drink 8 glasses of water',
      checkWaterSub:     '8 glasses a day',
      checkIron:         'Take iron + folic acid',
      checkIronSub:      'After lunch',
      checkWalk:         '15-minute gentle walk',
      checkWalkSub:      'Around sunset is best',
      checkKicks:        'Count baby kicks',
      checkKicksSub:     'Try after dinner',
      taraProud:         'Tara is so proud of you today! 🌸',
      forYourBodyToday:  'For your body today',
      eat:               'Eat',
      avoid:             'Avoid',
      breathingTitle:    'A 2-minute breathing moment',
      breathingSub:      'Tara will breathe with you. Whenever you need.',
      begin:             'Begin',
      riskAnalyserShort: 'Risk analyser',
      riskSubHome:       "Tell me how you feel — I'll tell you if it's worth a call.",
      nextCheckup:       'Next checkup',
      noCheckup:         'No upcoming checkup',
      bookCheckup:       'Schedule →',
      details:           'Details',
      thisMonth:         'This month →',
      week:              'WEEK',
      eatContent:        'Lentils, leafy greens, and 1 boiled egg',
      eatSub:            'Iron + folate for baby\'s brain growth.',
      avoidContent:      'Raw papaya, strong tea',
      avoidSub:          'And heavy lifting after lunch.',

      // ── Journey ───────────────────────────────────────────────
      yourJourney:             'Your journey',
      month:                   'Month',
      forYourBaby:             'For your baby',
      forYourBody:             'For your body',
      emotionalWeather:        'Emotional weather',
      emotionalWeatherText:    "Feelings may swing fast this month — calm, then teary, then proud, then anxious. That's not weakness. That's hormones building a person.",
      emotionalWeatherSub:     'If sadness lasts more than 2 weeks, please tell me. We can talk anytime.',
      monthTitle1:  'A tiny spark',
      monthTitle2:  'First flutter',
      monthTitle3:  'Becoming you',
      monthTitle4:  'A quieter calm',
      monthTitle5:  'First kicks',
      monthTitle6:  'Your voice, their world',
      monthTitle7:  'Slowing down',
      monthTitle8:  'Heavy and held',
      monthTitle9:  'Almost here',
      monthTitle10: 'First breath',
      monthTitle11: 'Finding rhythm',
      monthTitle12: 'Into the light',
      afterBirth:   'After Birth',
      exercise:        'Exercise',
      thisMonthTasks:  'This month',
      yourNewborn:     'Your newborn',
      yourRecovery:    'Your recovery',

      // ── Chat ──────────────────────────────────────────────────
      taraOpening:      "I'm Tara. How are you feeling?",
      chatPlaceholder:  'Tell Tara anything...',
      conversations:    'Conversations',
      newConversation:  'New conversation',
      noConversations:  'No conversations found',

      // ── Voice ─────────────────────────────────────────────────
      listeningLabel:   'listening',
      speakingLabel:    'speaking',
      mutedLabel:       'muted',
      mute:             'Mute',
      unmute:           'Unmute',
      speaker:          'Speaker',
      sayAnything:      '"Say anything — I\'m listening..."',
      youTalking:       "You're talking · I'm listening carefully",
      saySmth:          "Say something — I'm listening",
      taraThinking:     '"...thinking..."',

      // ── Wellness ──────────────────────────────────────────────
      forYourHeart:     'For your heart',
      howDoesToday:     'How does today',
      actuallyFeel:     'actually feel?',
      moodTender:       'Tender',
      moodOkay:         'Okay',
      moodTired:        'Tired',
      moodWorried:      'Worried',
      moodHeavy:        'Heavy',
      moodHappy:        'Happy',
      breatheIn:        'Breathe in...',
      hold:             'Hold...',
      breatheOut:       'Breathe out...',
      boxBreathing:     'Box breathing · 4·2·4',
      breatheWithTara:  'Breathe with Tara',
      breatheSub:       'Tara breathes when you breathe.',
      cycleCount:       'Cycle {n} · keep going',
      pause:            'Pause',
      fromTaraToday:    'From Tara, for today',
      swipe:            'swipe →',
      affirmation1:     'You are growing a person.\nThat is enough today.',
      affirmation2:     'Tired is allowed.\nRest is part of caring.',
      affirmation3:     'You are not alone.\nI am always here.',
      affirmation4:     'Whatever you feel\nis welcome here.',

      // ── Wellness v2 ───────────────────────────────────────────
      wellnessWeekCtx:  'Week {w} · {t}',
      wellnessPick:     "Tara's Pick",
      wellnessPickSub:  'Best for how you feel right now',
      wellnessLibrary:  'Browse Library',
      sessionBegin:     'Begin',
      sessionResume:    'Resume',
      catBreathe:       'Breathe',
      catMove:          'Move',
      catCalm:          'Calm',
      catSleep:         'Sleep',
      catAll:           'All',
      minLabel:         'min',
      allTrimesters:    'All trimesters',
      t1Label:          'T1',
      t2Label:          'T2',
      t3Label:          'T3',
      moodHistoryTitle: 'Your week in feelings',
      moodHistoryEmpty: 'Log a mood after a session to see your graph here',
      noSessionsFound:  'No sessions available for your week',
      sessionLoading:   'Finding the right session…',
      sessionError:     'Could not load sessions',
      // Session Player
      playerBack:       'Back',
      playerStep:       'Step {a} of {b}',
      playerPause:      'Pause',
      playerPlay:       'Resume',
      playerNext:       'Next',
      playerPrev:       'Previous',
      playerPostTitle:  'How do you feel now?',
      playerPostLog:    'Log & finish',
      playerPostSkip:   'Skip',
      playerDoneTitle:  'Well done',
      playerDoneSub:    'Tara is proud of you.',
      playerPreLabel:   'Getting ready…',
      pausePrompt:      'Take your time…',
      meditationTitle:  'Meditations for You',
      streakDays:       '🔥 {n}-day streak',
      streakStart:      'Start your streak today',
      streakToday:      'You meditated today ✓',

      // ── Care ──────────────────────────────────────────────────
      careForBoth:      'Care for you both',
      careTitle:        'Checkups, kicks,',
      careTitleItalic:  'and a calm path',
      needHelpNow:      'Need help, right now?',
      taraGuide:        'Tara will guide you, step by step. No panic.',
      iNeedHelp:        'I need help',
      hide:             'Hide',
      bleeding:         'I see bleeding',
      waterBroke:       'My water broke',
      sharpPain:        'Sharp or constant pain',
      babyNotMoved:     "Baby hasn't moved in hours",
      callDoctor:       'Just call my doctor now',
      taraStaysCalm:    "Tara stays calm with you. We'll get you safe.",

      // ── Risk ──────────────────────────────────────────────────
      forYourSafety:    'For your safety',
      riskAnalyser:     'Risk analyser',
      whatAreYouFeeling:'What are you feeling today?',
      tapAllThatApply:  'Tap all that apply',
      todaysReadings:   "Today's readings",
      riskSafe:         "Nothing flagged today. Keep doing what you're doing 🌸",
      riskLow:          'Probably normal pregnancy discomfort. Watch how it changes today.',
      riskModerate:     'Please tell your doctor today. Not urgent, but not ignoring either.',
      riskHigh:         "This needs care right away. Tara will help you make the call.",
      riskLabelSafe:    'All clear',
      riskLabelLow:     'Low concern',
      riskLabelModerate:'Worth a call',
      riskLabelHigh:    'Call now',
      analyseButton:    'Analyse with Maya AI',
      notMedical:       'Not a medical diagnosis · always call your doctor for emergencies',
      reset:            'Reset',
      symHeadache:      'Bad headache',
      symSwelling:      'Sudden swelling in face/hands',
      symVision:        'Blurry vision',
      symBleeding:      'Any bleeding',
      symPain:          'Sharp abdominal pain',
      symFever:         'Fever > 38°C',
      symKicks:         'Baby moving less today',
      symNausea:        'Cannot keep food down',
      symBreath:        'Trouble breathing',
      symMood:          'Feeling very low / hopeless',

      // ── Settings ──────────────────────────────────────────────
      settingsTitle:       'Settings',
      sectionLanguage:     'Language',
      howShouldTaraTalk:   'How should Tara talk to you?',
      switchAnytime:       'Switch anytime · she understands both',
      sectionNotifications:'Notifications',
      notifDaily:          "Tara's daily check-in",
      notifDailySub:       "9:00 AM · we'll start the day together",
      notifKicks:          'Kick count reminders',
      notifKicksSub:       'Evenings after dinner',
      notifMeds:           'Iron + folic acid reminder',
      notifMedsSub:        'After lunch',
      notifMood:           'Mood check-ins',
      notifMoodSub:        'Twice a week',
      sectionVoice:        'Voice & appearance',
      wakeOnHiTara:        "Wake on 'Hi Tara'",
      wakeOnHiTaraSub:     'Listen even when app is closed',

      // ── Profile ───────────────────────────────────────────────
      yourProfile:        'Your profile',
      motherToBe:         'Mother-to-be',
      fieldName:          'Name',
      fieldWeek:          'Pregnancy week',
      fieldAge:           'Age',
      fieldCity:          'City',
      fieldBlood:         'Blood group',
      fieldFirstPreg:     'First pregnancy',
      fieldLang:          'Language preference',
      fieldGuardianName:  'Guardian name',
      fieldGuardianPhone: 'Guardian phone',
      fieldDoctorName:    "Doctor's name",
      fieldDoctorEmail:   "Doctor's email",
      doctorCardTitle:    'My doctor',
      addDoctorPrompt:    "Add your doctor's email — Tara can alert them",
      alertDoctor:        'Alert doctor',
      doctorAlerted:      'Doctor notified',
      editProfile:        'Edit profile',
      saveChanges:        'Save changes',
      cancel:             'Cancel',
      saving:             'Saving…',
      healthSnapshot:     'Health snapshot',
      careCircle:         'Your care circle',
      firstPregYes:       'Yes',
      firstPregNo:        'No',

      // ── Onboarding ────────────────────────────────────────────
      ob1Title:   'Hello, mama-to-be 🌸',
      ob1Sub:     "I'm Tara. I'll be your companion through every soft, scary, beautiful day.",
      ob1Action:  'Nice to meet you',
      ob2Title:   'A friend, not a doctor',
      ob2Sub:     'I listen, I encourage, I help you remember to drink water and breathe. For medical things, I gently point you to real care.',
      ob2Action:  'Got it',
      ob3Title:   'When you talk, I show up',
      ob3Sub:     'Type or speak to me anytime — in বাংলা or English. My face shows that I really hear you.',
      ob3Action:  "Let's begin",
      skipIntro:  'Skip intro',

      // ── BottomNav ─────────────────────────────────────────────
      nav_home:    'Home',
      nav_journey: 'Journey',
      nav_heart:   'Heart',
      nav_care:    'Care',
    },

    bn: {
      // ── Home ──────────────────────────────────────────────────
      greeting:          'শুভ সকাল',
      taraIsHere:        'তারা এখানে আছে',
      taraHeroSub:       'আমি আজ আপনার পাশেই আছি। কথা বলতে ট্যাপ করুন।',
      chatWithTara:      'তারার সাথে কথা বলুন',
      voice:             'ভয়েস',
      babyThisWeek:      'এই সপ্তাহে শিশু',
      sizeOfA:           'আকারে একটি',
      weeksToGo:         'আর {n} সপ্তাহ বাকি',
      weeksPostpartum:   'প্রসবের {n} সপ্তাহ পর',
      monthOf9:          '{n} মাস / ৯ এর মধ্যে',
      trimester1:        'প্রথম ত্রৈমাসিক',
      trimester2:        'দ্বিতীয় ত্রৈমাসিক',
      trimester3:        'তৃতীয় ত্রৈমাসিক',
      todaysCare:        'আজকের যত্ন',
      checkWater:        '৮ গ্লাস পানি পান করুন',
      checkWaterSub:     'প্রতিদিন ৮ গ্লাস',
      checkIron:         'আয়রন + ফলিক এ্যাসিড নিন',
      checkIronSub:      'দুপুরের খাবারের পর',
      checkWalk:         '১৫ মিনিট হাঁটুন',
      checkWalkSub:      'সন্ধ্যার দিকে ভালো',
      checkKicks:        'শিশুর লাথি গুণুন',
      checkKicksSub:     'রাতের খাবারের পর',
      taraProud:         'তারা আজ আপনার জন্য গর্বিত! 🌸',
      forYourBodyToday:  'আজ আপনার শরীরের জন্য',
      eat:               'খাবার',
      avoid:             'এড়িয়ে চলুন',
      breathingTitle:    '২ মিনিটের শ্বাস-প্রশ্বাস মুহূর্ত',
      breathingSub:      'তারা আপনার সাথে শ্বাস নেবে। যখনই দরকার।',
      begin:             'শুরু করুন',
      riskAnalyserShort: 'ঝুঁকি বিশ্লেষক',
      riskSubHome:       'আপনি কেমন অনুভব করছেন বলুন — আমি বলব চিন্তার কিছু আছে কিনা।',
      nextCheckup:       'পরবর্তী চেকআপ',
      noCheckup:         'কোনো চেকআপ নির্ধারিত নেই',
      bookCheckup:       'বুক করুন →',
      details:           'বিস্তারিত',
      thisMonth:         'এই মাস →',
      week:              'সপ্তাহ',
      eatContent:        'ডাল, শাকসবজি এবং ১টি সিদ্ধ ডিম',
      eatSub:            'শিশুর মস্তিষ্কের জন্য আয়রন ও ফোলেট।',
      avoidContent:      'কাঁচা পেঁপে, গাঢ় চা',
      avoidSub:          'এবং দুপুরের পর ভারী কাজ।',

      // ── Journey ───────────────────────────────────────────────
      yourJourney:          'আপনার যাত্রা',
      month:                'মাস',
      forYourBaby:          'আপনার শিশুর জন্য',
      forYourBody:          'আপনার শরীরের জন্য',
      emotionalWeather:     'আবেগের আবহাওয়া',
      emotionalWeatherText: 'এই মাসে অনুভূতি দ্রুত পাল্টাতে পারে — শান্ত, তারপর কান্না, তারপর গর্ব, তারপর উদ্বেগ। এটা দুর্বলতা নয়। এটা হরমোন একটি মানুষ গড়ছে।',
      emotionalWeatherSub:  'যদি দুঃখ ২ সপ্তাহের বেশি থাকে, দয়া করে আমাকে জানান। আমরা যেকোনো সময় কথা বলতে পারি।',
      monthTitle1:  'একটি ছোট্ট স্ফুলিঙ্গ',
      monthTitle2:  'প্রথম কম্পন',
      monthTitle3:  'তুমি হয়ে উঠছ',
      monthTitle4:  'শান্ত এক অনুভূতি',
      monthTitle5:  'প্রথম লাথি',
      monthTitle6:  'তোমার কণ্ঠস্বর, তাদের জগৎ',
      monthTitle7:  'ধীরে চলা',
      monthTitle8:  'ভারী ও আদরে',
      monthTitle9:  'প্রায় এসে গেছে',
      monthTitle10: 'প্রথম শ্বাস',
      monthTitle11: 'তাল খুঁজে নেওয়া',
      monthTitle12: 'আলোর দিকে',
      afterBirth:   'জন্মের পর',
      exercise:        'ব্যায়াম',
      thisMonthTasks:  'এই মাস',
      yourNewborn:     'আপনার নবজাতক',
      yourRecovery:    'আপনার সুস্থতা',

      // ── Chat ──────────────────────────────────────────────────
      taraOpening:      'আমি তারা। কেমন আছেন?',
      chatPlaceholder:  'তারাকে যা খুশি বলুন...',
      conversations:    'কথোপকথন',
      newConversation:  'নতুন কথোপকথন',
      noConversations:  'কোনো কথোপকথন পাওয়া যায়নি',

      // ── Voice ─────────────────────────────────────────────────
      listeningLabel:  'শুনছি',
      speakingLabel:   'বলছি',
      mutedLabel:      'নিঃশব্দ',
      mute:            'নিঃশব্দ',
      unmute:          'সক্রিয় করুন',
      speaker:         'স্পিকার',
      sayAnything:     '"বলুন — আমি শুনছি..."',
      youTalking:      'আপনি বলছেন · আমি মনোযোগ দিয়ে শুনছি',
      saySmth:         'কিছু বলুন — আমি শুনছি',
      taraThinking:    '"...আমি ভাবছি..."',

      // ── Wellness ──────────────────────────────────────────────
      forYourHeart:    'আপনার মনের জন্য',
      howDoesToday:    'আজকের দিনটা',
      actuallyFeel:    'আসলে কেমন লাগছে?',
      moodTender:      'কোমল',
      moodOkay:        'ঠিকই আছি',
      moodTired:       'ক্লান্ত',
      moodWorried:     'চিন্তিত',
      moodHeavy:       'ভারাক্রান্ত',
      moodHappy:       'খুশি',
      breatheIn:       'শ্বাস নিন...',
      hold:            'ধরুন...',
      breatheOut:      'শ্বাস ছাড়ুন...',
      boxBreathing:    'বক্স ব্রিদিং · ৪·২·৪',
      breatheWithTara: 'তারার সাথে শ্বাস নিন',
      breatheSub:      'তারা আপনার সাথে শ্বাস নেয়।',
      cycleCount:      'চক্র {n} · চলুন',
      pause:           'বিরতি',
      fromTaraToday:   'তারার কাছ থেকে, আজকের জন্য',
      swipe:           'সোয়াইপ →',
      affirmation1:    'আপনি একজন মানুষ বড় করছেন।\nআজকের জন্য এটাই যথেষ্ট।',
      affirmation2:    'ক্লান্ত হওয়া স্বাভাবিক।\nবিশ্রাম যত্নের অংশ।',
      affirmation3:    'আপনি একা নন।\nআমি সবসময় আছি।',
      affirmation4:    'আপনি যা-ই অনুভব করুন\nএখানে স্বাগত।',

      // ── Wellness v2 ───────────────────────────────────────────
      wellnessWeekCtx:  'সপ্তাহ {w} · {t}',
      wellnessPick:     'তারার পছন্দ',
      wellnessPickSub:  'আপনার অনুভূতির জন্য সেরা',
      wellnessLibrary:  'সব সেশন দেখুন',
      sessionBegin:     'শুরু করুন',
      sessionResume:    'চালিয়ে যান',
      catBreathe:       'শ্বাস',
      catMove:          'নড়াচড়া',
      catCalm:          'শান্তি',
      catSleep:         'ঘুম',
      catAll:           'সব',
      minLabel:         'মিনিট',
      allTrimesters:    'সব ত্রৈমাসিক',
      t1Label:          'ট্রি১',
      t2Label:          'ট্রি২',
      t3Label:          'ট্রি৩',
      moodHistoryTitle: 'আপনার সপ্তাহের অনুভূতি',
      moodHistoryEmpty: 'সেশনের পরে মেজাজ লগ করুন',
      noSessionsFound:  'এই সপ্তাহের জন্য কোনো সেশন পাওয়া যায়নি',
      sessionLoading:   'সঠিক সেশন খোঁজা হচ্ছে…',
      sessionError:     'সেশন লোড করা যায়নি',
      // Session Player
      playerBack:       'ফিরে যান',
      playerStep:       'ধাপ {a} / {b}',
      playerPause:      'বিরতি',
      playerPlay:       'চালিয়ে যান',
      playerNext:       'পরের',
      playerPrev:       'আগের',
      playerPostTitle:  'এখন কেমন লাগছে?',
      playerPostLog:    'সেভ করুন',
      playerPostSkip:   'এড়িয়ে যান',
      playerDoneTitle:  'শাবাশ',
      playerDoneSub:    'তারা আপনার জন্য গর্বিত।',
      playerPreLabel:   'প্রস্তুত হচ্ছি…',
      pausePrompt:      'সময় নিন…',
      meditationTitle:  'আপনার জন্য ধ্যান',
      streakDays:       '🔥 {n} দিনের ধারা',
      streakStart:      'আজ থেকে শুরু করুন',
      streakToday:      'আজ ধ্যান করেছেন ✓',

      // ── Care ──────────────────────────────────────────────────
      careForBoth:     'আপনাদের দুজনের যত্ন',
      careTitle:       'চেকআপ, লাথি,',
      careTitleItalic: 'এবং একটি শান্ত পথ',
      needHelpNow:     'এখনই সাহায্য দরকার?',
      taraGuide:       'তারা আপনাকে ধাপে ধাপে গাইড করবে। ঘাবড়াবেন না।',
      iNeedHelp:       'আমার সাহায্য দরকার',
      hide:            'বন্ধ করুন',
      bleeding:        'রক্তপাত হচ্ছে',
      waterBroke:      'পানি ভেঙে গেছে',
      sharpPain:       'তীব্র বা ক্রমাগত ব্যথা',
      babyNotMoved:    'শিশু ঘণ্টার পর ঘণ্টা নড়েনি',
      callDoctor:      'এখনই ডাক্তারকে কল করুন',
      taraStaysCalm:   'তারা আপনার সাথে শান্ত থাকে। আমরা আপনাকে নিরাপদ করব।',

      // ── Risk ──────────────────────────────────────────────────
      forYourSafety:    'আপনার নিরাপত্তার জন্য',
      riskAnalyser:     'ঝুঁকি বিশ্লেষক',
      whatAreYouFeeling:'আজ আপনি কেমন অনুভব করছেন?',
      tapAllThatApply:  'সব প্রযোজ্যতে ট্যাপ করুন',
      todaysReadings:   'আজকের পড়া',
      riskSafe:         'আজ কোনো সমস্যা নেই। এভাবেই চলুন 🌸',
      riskLow:          'সম্ভবত স্বাভাবিক গর্ভাবস্থার অস্বস্তি। আজ কীভাবে পরিবর্তন হয় লক্ষ্য রাখুন।',
      riskModerate:     'আজ আপনার ডাক্তারকে জানান। জরুরি নয়, তবে উপেক্ষা করবেন না।',
      riskHigh:         'এখনই যত্ন দরকার। তারা আপনাকে কল করতে সাহায্য করবে।',
      riskLabelSafe:    'সব ঠিক',
      riskLabelLow:     'সামান্য উদ্বেগ',
      riskLabelModerate:'একটু কল করুন',
      riskLabelHigh:    'এখনই কল করুন',
      analyseButton:    'Maya AI দিয়ে বিশ্লেষণ করুন',
      notMedical:       'এটি চিকিৎসা নির্ণয় নয় · জরুরি পরিস্থিতিতে সবসময় ডাক্তার ডাকুন',
      reset:            'রিসেট',
      symHeadache:      'তীব্র মাথাব্যথা',
      symSwelling:      'মুখ/হাতে হঠাৎ ফোলাভাব',
      symVision:        'ঝাপসা দৃষ্টি',
      symBleeding:      'যেকোনো রক্তপাত',
      symPain:          'তীব্র পেটের ব্যথা',
      symFever:         'জ্বর > ৩৮°সে',
      symKicks:         'আজ শিশু কম নড়ছে',
      symNausea:        'খাবার রাখা যাচ্ছে না',
      symBreath:        'শ্বাস নিতে কষ্ট হচ্ছে',
      symMood:          'খুব মন খারাপ / হতাশ লাগছে',

      // ── Settings ──────────────────────────────────────────────
      settingsTitle:        'সেটিংস',
      sectionLanguage:      'ভাষা',
      howShouldTaraTalk:    'তারা কীভাবে আপনার সাথে কথা বলবে?',
      switchAnytime:        'যেকোনো সময় পরিবর্তন করুন · সে দুটোই বোঝে',
      sectionNotifications: 'বিজ্ঞপ্তি',
      notifDaily:           'তারার দৈনিক চেক-ইন',
      notifDailySub:        'সকাল ৯:০০ · আমরা একসাথে দিন শুরু করব',
      notifKicks:           'লাথি গণনার রিমাইন্ডার',
      notifKicksSub:        'রাতের খাবারের পর',
      notifMeds:            'আয়রন + ফলিক এ্যাসিড রিমাইন্ডার',
      notifMedsSub:         'দুপুরের পর',
      notifMood:            'মেজাজ চেক-ইন',
      notifMoodSub:         'সপ্তাহে দুবার',
      sectionVoice:         'ভয়েস এবং চেহারা',
      wakeOnHiTara:         "'হ্যালো তারা' বলে জাগান",
      wakeOnHiTaraSub:      'অ্যাপ বন্ধ থাকলেও শুনবে',

      // ── Profile ───────────────────────────────────────────────
      yourProfile:        'আপনার প্রোফাইল',
      motherToBe:         'মা হতে চলেছেন',
      fieldName:          'নাম',
      fieldWeek:          'গর্ভাবস্থার সপ্তাহ',
      fieldAge:           'বয়স',
      fieldCity:          'শহর',
      fieldBlood:         'রক্তের গ্রুপ',
      fieldFirstPreg:     'প্রথম গর্ভাবস্থা',
      fieldLang:          'ভাষার পছন্দ',
      fieldGuardianName:  'অভিভাবকের নাম',
      fieldGuardianPhone: 'অভিভাবকের ফোন',
      fieldDoctorName:    'ডাক্তারের নাম',
      fieldDoctorEmail:   'ডাক্তারের ইমেইল',
      doctorCardTitle:    'আমার ডাক্তার',
      addDoctorPrompt:    'ডাক্তারের ইমেইল যোগ করুন — তারা তাঁকে সতর্ক করতে পারবে',
      alertDoctor:        'ডাক্তারকে সতর্ক করুন',
      doctorAlerted:      'ডাক্তারকে জানানো হয়েছে',
      editProfile:        'প্রোফাইল সম্পাদনা',
      saveChanges:        'পরিবর্তন সংরক্ষণ করুন',
      cancel:             'বাতিল',
      saving:             'সংরক্ষণ হচ্ছে…',
      healthSnapshot:     'স্বাস্থ্যের সারসংক্ষেপ',
      careCircle:         'আপনার যত্নের বৃত্ত',
      firstPregYes:       'হ্যাঁ',
      firstPregNo:        'না',

      // ── Onboarding ────────────────────────────────────────────
      ob1Title:   'হ্যালো, মা হতে চলেছেন 🌸',
      ob1Sub:     'আমি তারা। প্রতিটি নরম, ভয়ের, সুন্দর দিনে আমি আপনার সঙ্গী হব।',
      ob1Action:  'পরিচিত হলাম',
      ob2Title:   'বন্ধু, ডাক্তার নই',
      ob2Sub:     'আমি শুনি, উৎসাহ দিই, পানি পান ও শ্বাস নিতে মনে করিয়ে দিই। চিকিৎসার বিষয়ে, আমি সত্যিকারের যত্নের দিকে নিয়ে যাই।',
      ob2Action:  'বুঝলাম',
      ob3Title:   'আপনি কথা বললে, আমি শুনি',
      ob3Sub:     'বাংলা বা English যেকোনো ভাষায় টাইপ বা কথা বলুন। আমার মুখ দেখায় যে আমি সত্যিই শুনছি।',
      ob3Action:  'শুরু করি',
      skipIntro:  'ভূমিকা এড়িয়ে যান',

      // ── BottomNav ─────────────────────────────────────────────
      nav_home:    'হোম',
      nav_journey: 'যাত্রা',
      nav_heart:   'হৃদয়',
      nav_care:    'যত্ন',
    },
  };

  // Resolver: type='tara' → Bangla in mixed, type='ui' → English in mixed
  window.tStr = function (key, lang, type) {
    if (type === undefined) type = 'ui';
    var l = lang === 'mixed' ? (type === 'tara' ? 'bn' : 'en') : (lang || 'en');
    var dict = MAYA_STRINGS[l] || MAYA_STRINGS.en;
    var val = dict[key];
    if (val !== undefined) return val;
    val = MAYA_STRINGS.en[key];
    if (val !== undefined) return val;
    return key; // raw key — never blank, never throws
  };

  window.MAYA_STRINGS = MAYA_STRINGS;
})();
